apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      microservice: auth
  replicas: 1
  template:
    metadata:
      labels:
        microservice: auth
    spec:
      containers:
      - name: auth-deployment
        image: localhost:5555/mc-microservices-auth
        ports:
            - containerPort: 3000
        env:   
        - name: AMQP_URL
          valueFrom:
            configMapKeyRef:   
              name: env-config-map
              key: AMQP_URL
