apiVersion: v1
kind: Service
metadata:
  name: mc-v2-mongodb-lynx
spec:
  type: ExternalName
  selector:
    db: mc-v2-mongodb-lynx
  externalName: host.docker.internal
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
