apiVersion: v1
kind: Service
metadata:
  name: mc-v2-mongodb-puma
spec:
  type: ExternalName
  selector:
    db: mc-v2-mongodb-puma
  externalName: host.docker.internal
  ports:
    - port: 27018
      targetPort: 27018
      protocol: TCP
