apiVersion: v1
kind: Service
metadata:
  name: mc-v2-mongodb-wolf
spec:
  type: ExternalName
  selector:
    db: mc-v2-mongodb-wolf
  externalName: host.docker.internal
  ports:
    - port: 27019
      targetPort: 27019
      protocol: TCP
