apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      broker: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        broker: rabbitmq
    spec:
      containers:
      - name: rabbitmq-deployment
        image: rabbitmq:3-management
        ports:
            - containerPort: 5672
            - containerPort: 15672
