apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
spec:
  selector:
    matchLabels:
      microservice: health
  replicas: 1
  template:
    metadata:
      labels:
        microservice: health
    spec:
      containers:
      - name: health-deployment
        image: localhost:5555/mc-microservices-health
        ports:
            - containerPort: 3000
        env:   
        - name: AMQP_URL
          valueFrom:
            configMapKeyRef:   
              name: env-config-map
              key: AMQP_URL
        - name: DB_URL
          valueFrom:
            configMapKeyRef:   
              name: env-config-map
              key: DB_URL
